export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCEEDED = 'CREATE_POST_SUCCEEDED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCEEDED = 'DELETE_POST_SUCCEEDED';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';
